language: objective-c
install: bundle install
before_install:
- (ruby --version)
- sudo chown -R travis ~/Library/RubyMotion
- mkdir -p ~/Library/RubyMotion/build
- pod setup
- bundle exec rake pod:install
script: bundle exec rake spec
env:
  global:
  - COCOAPODS_NO_REPO_UPDATE_OUTPUT=true